name: 'PagerDuty Alert'
description: 'GitHub Action to send a critical PagerDuty alert, e.g. on action failure.'
inputs:
  pagerduty-integration-key:
    description: 'The integration key for your PagerDuty service'
    required: true
  severity:
    description: 'Alert severity (critical, error, warning or info)'
    required: false    
  source:
    description: 'The source of the alert'
    required: false
  summary:
    description: 'The summary to send to PagerDuty'
    required: false
  pagerduty-dedup-key:
    description: 'The key used to correlate PagerDuty triggers, acknowledges, and resolves for the same alert.'
    required: false    
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'alert-triangle'
  color: 'red'